#!/usr/bin/env python3
"""Generate hub-switch mapping artifacts from a single canonical JSON contract."""

from __future__ import annotations

import json
from pathlib import Path


WORLD_DIR = Path(__file__).resolve().parents[1]
CONTRACT_PATH = WORLD_DIR / "data" / "hub_switch_contract.json"
LOCATIONS_PATH = WORLD_DIR / "data" / "locations.json"
PY_OUT_PATH = WORLD_DIR / "generated_hub_switch_contract.py"
C_INC_OUT_PATH = WORLD_DIR / "kirby_ap_payload" / "generated_hub_switch_worldmap_cases.inc"


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _validate_contract(contract: dict, locations: dict) -> list[dict]:
    schema_version = int(contract.get("schema_version", 0))
    if schema_version != 1:
        raise ValueError(f"Unsupported hub_switch_contract schema_version: {schema_version}")

    entries = contract.get("entries")
    if not isinstance(entries, list) or not entries:
        raise ValueError("hub_switch_contract entries must be a non-empty list")

    seen_door_indices: set[int] = set()
    seen_ap_bits: set[int] = set()

    normalized: list[dict] = []
    for raw in entries:
        location_key = str(raw["location_key"])
        door_index = int(raw["native_world_map_door_index"])
        door_name = str(raw["native_world_map_door_name"])
        ap_bit = int(raw["ap_bit_index"])
        compatibility_bits = tuple(int(v) for v in raw.get("compatibility_ap_bits", []))

        if location_key not in locations:
            raise ValueError(f"Contract references missing location key: {location_key}")
        location_meta = locations[location_key]
        if str(location_meta.get("category")) != "HUB_SWITCH":
            raise ValueError(f"Contract location must be HUB_SWITCH: {location_key}")

        declared_bit = int(location_meta["bit_index"])
        if declared_bit != ap_bit:
            raise ValueError(
                f"Contract ap_bit_index mismatch for {location_key}: contract={ap_bit} locations.json={declared_bit}"
            )

        if door_index in seen_door_indices:
            raise ValueError(f"Duplicate native_world_map_door_index in contract: {door_index}")
        if ap_bit in seen_ap_bits:
            raise ValueError(f"Duplicate ap_bit_index in contract: {ap_bit}")

        seen_door_indices.add(door_index)
        seen_ap_bits.add(ap_bit)
        normalized.append(
            {
                "location_key": location_key,
                "native_world_map_door_index": door_index,
                "native_world_map_door_name": door_name,
                "ap_bit_index": ap_bit,
                "compatibility_ap_bits": compatibility_bits,
            }
        )

    return normalized


def _build_python_output(entries: list[dict]) -> str:
    lines: list[str] = []
    lines.append('"""Generated hub-switch mapping contract.')
    lines.append("")
    lines.append("DO NOT EDIT MANUALLY.")
    lines.append("Source: worlds/kirbyam/data/hub_switch_contract.json")
    lines.append("Generated by: worlds/kirbyam/tools/generate_hub_switch_contract.py")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from typing import Final")
    lines.append("")
    lines.append("")
    lines.append("HUB_SWITCH_WORLD_MAP_DOOR_TO_AP_BIT: Final[dict[int, int]] = {")
    for entry in entries:
        lines.append(f"    {entry['native_world_map_door_index']}: {entry['ap_bit_index']},")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("HUB_SWITCH_LOCATION_KEY_BY_AP_BIT: Final[dict[int, str]] = {")
    for entry in entries:
        lines.append(f"    {entry['ap_bit_index']}: \"{entry['location_key']}\",")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("HUB_SWITCH_COMPATIBILITY_AP_BITS_BY_LOCATION_KEY: Final[dict[str, tuple[int, ...]]] = {")
    for entry in entries:
        compatibility_bits: tuple[int, ...] = entry["compatibility_ap_bits"]
        if compatibility_bits:
            bit_values = ", ".join(str(v) for v in compatibility_bits)
            if len(compatibility_bits) == 1:
                bit_values += ","
            lines.append(f"    \"{entry['location_key']}\": ({bit_values}),")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _build_c_include_output(entries: list[dict]) -> str:
    lines: list[str] = []
    lines.append("/*")
    lines.append(" * Generated hub-switch world-map door mapping.")
    lines.append(" * DO NOT EDIT MANUALLY.")
    lines.append(" * Source: worlds/kirbyam/data/hub_switch_contract.json")
    lines.append(" * Generated by: worlds/kirbyam/tools/generate_hub_switch_contract.py")
    lines.append(" */")
    for entry in entries:
        door_index = entry["native_world_map_door_index"]
        door_name = entry["native_world_map_door_name"]
        ap_bit = entry["ap_bit_index"]
        lines.append(f"case {door_index}u: /* {door_name} */")
        lines.append(f"    *out_bit = {ap_bit}u;")
        lines.append("    return 1u;")
    lines.append("default:")
    lines.append("    return 0u;")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    contract = _load_json(CONTRACT_PATH)
    locations = _load_json(LOCATIONS_PATH)
    entries = _validate_contract(contract, locations)

    PY_OUT_PATH.write_text(_build_python_output(entries), encoding="utf-8")
    C_INC_OUT_PATH.write_text(_build_c_include_output(entries), encoding="utf-8")

    print(f"Wrote {PY_OUT_PATH}")
    print(f"Wrote {C_INC_OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
